apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespaces.yaml
  - ../configmaps.yaml
  - ../network-policy.yaml
  - customer-service.yaml
  - policy-service.yaml
  - claims-service.yaml
  - payment-service.yaml
  - tier1-services.yaml
  - tier2-services.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: insurance-platform
