apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: ns-infra
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-0.kafka-headless.ns-infra.svc.cluster.local:9092,kafka-1.kafka-headless.ns-infra.svc.cluster.local:9092,kafka-2.kafka-headless.ns-infra.svc.cluster.local:9092"
  KAFKA_BOOTSTRAP: "kafka-0.kafka-headless.ns-infra.svc.cluster.local:9092,kafka-1.kafka-headless.ns-infra.svc.cluster.local:9092,kafka-2.kafka-headless.ns-infra.svc.cluster.local:9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: ns-infra
data:
  KEYCLOAK_JWK_URI: "http://keycloak.ns-infra.svc.cluster.local:8080/realms/insurance/protocol/openid-connect/certs"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: ns-infra
data:
  REDIS_HOST: "redis.ns-infra.svc.cluster.local"
  REDIS_PORT: "6379"
